name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      all: ${{ steps.changes.outputs.all }}
      markdown: ${{ steps.changes.outputs.markdown }}
    steps:
      # Make sure we have some code to diff
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changes
        # Set outputs using the command
        run: |
          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | xargs)"
          echo "::set-output name=markdown::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep .md$ | xargs)"

  checkforchangelog:
    runs-on: ubuntu-latest
    needs: changedfiles
    steps:
      - name: echo changed files
        run: |
          if [[ ! "${{needs.changedfiles.outputs.markdown}}" == *"CHANGELOG.md"* ]]; then
            echo "::error file=CHANGELOG.md,line=1,col=1::Please make sure that you add a CHANGELOG entry to describe the changes in this pull request."
            exit 1
          fi

  lint:
    name: rome ci (ubuntu-latest)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.16.0'
      - name: rome ci
        run: ./rome ci

  tests:
    name: rome test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.16.0'
      - name: rome test
        run: ./rome test --freeze-snapshots

  typescript:
    runs-on: ubuntu-latest
    name: TypeScript Check

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.16.0'
      - name: Run TypeScript
        run: node ./node_modules/.bin/tsc --noEmit

  generated:
    name: Generated Files Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.16.0'
      - name: Check if generated files need to be updated
        run: ./rome run scripts/generate-all-files
